### ISSUE TITLE
font size for date, time, etc...

### ISSUE THREAD

**Issue by GriefNorth** [sejjy/mechabar#18]
**How can I change the font in custom modules?**  

I increased the font size:  
```css
* {
  font-family: "JetBrainsMono Nerd Font";
  font-size: 16px;
  font-weight: bold;
}
```  
But it didn’t help.  
If I disable animation.css, the font starts working, but the tray module stops working.
