### ISSUE TITLE
Making the background blur instead of solid

### ISSUE THREAD

**Issue by No1really** [sejjy/mechabar#7]
Just how the title says, is there a way for making the background transparent? I can manually change the colors for the widgets, but I don't understand how to go about the background.

**Comment by sejjy** [comment]
Hi,

In **line 13**, you can change `background: @main-bg` to `background: transparent` to achieve that. You will also need to update the background colors of the **arrows**. Starting from **line 114**, the CSS elements, from top to bottom, correspond to the position of Waybar elements from left to right for easier editing.

If you only want to change the _inner_ background, try adjusting **lines 13 and 19**. 

Hope this helps :)

Best,
Jesse

**Comment by sejjy** [comment]
Lines **10** to **22**:

```css
/* === Main Background === */

window#waybar {
  background: @main-bg;
}

/* === Drop Shadow === */

window#waybar > box {
  background-color: transparent;
  box-shadow: 0 0 2px 1px rgba(0, 0, 0, 1);
  margin: 2px;
}
```
